SET FOREIGN_KEY_CHECKS =0;

create or replace view syn_server_status
as select ID,CREATETIME,UPDATETIME,DOWNTIME,ISLIVE from zyc_stlf_nw.syn_server_status;

create or replace view syn_job_conf
as select JOBID,JOBNAME,CRON,SRCSQL,SRCTABLEFIELDS,DESTTABLE,DESTTABLEFIELDS,DESTTABLEKEY,DESTTABLEUPDATE,SYNCOUNT from zyc_stlf_nw.syn_job_conf;

DROP TABLE IF EXISTS lf_his_96lc_syn;
CREATE TABLE lf_his_96lc_syn (
	ID INT ( 11 ) NOT NULL AUTO_INCREMENT COMMENT '自增ID，每条新增记录自增',
	JOBID INT(11) NOT NULL COMMENT '关联SYN_JOB_CONF表的JOBID 获取同步表名',
	BUSID INT(11) NOT NULL,
  CALIBERID VARCHAR(6) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL,
  YMD VARCHAR(8) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL,
	CREATETIME timestamp NOT NULL COMMENT '创建时间',
	SYNTIME timestamp NULL COMMENT '同步完成时间',
	ENV INT(2) NOT NULL COMMENT '主调->备调(0),备调->主调(1)',
	OPEARATE INT(2) NOT NULL COMMENT 'insert or update(0),delete(1)',
	SYNCOUNT INT(2) DEFAULT 1 COMMENT '需要同步次数，每次修改所需同步表(如base_bus)时此值加1，避免同步时又对所需同步表作修改造成的部分数据缺失',
	SYNSTATUS INT(2) NOT NULL COMMENT '同步状态(0：未同步；1：开始同步；2：完成同步)',
	PRIMARY KEY ( ID ) ,
	UNIQUE (BUSID,CALIBERID,YMD),
	KEY INDEX_UID_01 (BUSID,CALIBERID,YMD),
	KEY INDEX__ESS_01 (ENV,SYNCOUNT,SYNSTATUS),
	KEY INDEX_EOSS_01 (ENV,OPEARATE,SYNCOUNT,SYNSTATUS),
	FOREIGN KEY (JOBID) REFERENCES syn_job_conf(JOBID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT ='主备数据同步状态表，每个需要同步的表对应一个';


INSERT INTO `syn_server_status`(`id`, `createtime`, `updatetime`, `downtime`, `islive`) VALUES (1, '2020-10-31 09:03:00', '2020-10-31 09:03:00', NULL, 0);

-- 对需要同步的表新增字段
-- UPDATE lf_his_96lc SET LASTTIME ='2020-04-26 09:03:00' WHERE YMD ='20210101';
alter table base_substation add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_01 ON base_substation(LASTTIME);

alter table base_bus add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_02 ON base_bus(LASTTIME);

alter table base_acline add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_03 ON base_acline(LASTTIME);

alter table base_unit add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_04 ON base_unit(LASTTIME);

alter table base_transformer add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_05 ON base_transformer(LASTTIME);

alter table lf_his_96lc_base add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_06 ON lf_his_96lc_base(LASTTIME);

alter table lf_his_96lc add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_07 ON lf_his_96lc(LASTTIME);

alter table lf_q_his_96lc add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_08 ON lf_q_his_96lc(LASTTIME);

alter table BUS_LOAD_REPAIR_LOG add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_09 ON BUS_LOAD_REPAIR_LOG(LASTTIME);

alter table BUS_FC_96LC_SUBMIT add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_10 ON BUS_FC_96LC_SUBMIT(LASTTIME);

alter table BUS_FC_Q_96LC_SUBMIT add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_11 ON BUS_FC_Q_96LC_SUBMIT(LASTTIME);

alter table BUS_FC_96LC_SUBMIT_MODIFY add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_12 ON BUS_FC_96LC_SUBMIT_MODIFY(LASTTIME);

alter table BUS_FC_96LC add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_13 ON BUS_FC_96LC(LASTTIME);

SET FOREIGN_KEY_CHECKS =1;