SET FOREIGN_KEY_CHECKS =0;
DROP TABLE IF EXISTS syn_server_status;
CREATE TABLE syn_server_status (
	ID INT ( 11 ) NOT NULL AUTO_INCREMENT COMMENT '自增ID，主机每次DOWN->UP 自增',
	CREATETIME timestamp NOT NULL COMMENT '创建ISLIVE时间(主库维护)',
	UPDATETIME timestamp NULL COMMENT '更新ISLIVE时间(主库维护)',
	DOWNTIME timestamp NULL COMMENT '主库宕机时间(备库维护)',
	ISLIVE INT(2) COMMENT '主机状态(主备调维护 0：运行，1：宕机)',
	PRIMARY KEY ( ID )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='主服务器运行状态表';

DROP TABLE IF EXISTS syn_job_conf;
CREATE TABLE syn_job_conf (
	JOBID INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID，每条新增记录自增',
	JOBNAME VARCHAR (30) COMMENT '任务名称,作数据库区分 0：短期,1:220KV,2:500KV',
	CRON VARCHAR(20) NOT NULL COMMENT '任务表达式',
	SRCSQL VARCHAR(600) DEFAULT '*' COMMENT '源数据源SQL(默认为SELECT * FROM TABLENAME)',
	SRCTABLEFIELDS VARCHAR(600) DEFAULT '*' COMMENT '源数据表字段(默认为所有字段)',
	DESTTABLE VARCHAR(50) NOT NULL COMMENT '目的数据表(若SRCSQL不设置，则默认源和目标同表)',
	DESTTABLEFIELDS VARCHAR(600) DEFAULT '*' COMMENT '目标数据表字段(默认为所有字段)',
	DESTTABLEKEY VARCHAR(30) COMMENT '目标表主键',
	DESTTABLEUPDATE VARCHAR(600) COMMENT '目标表更新字段',
	SYNCOUNT INT(4) NOT NULL COMMENT '同步天数',
	PRIMARY KEY ( JOBID )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT ='主备数据同步配置表';


-- 同步表
DROP TABLE IF EXISTS lf_his_96lc_syn;
CREATE TABLE lf_his_96lc_syn (
	SJCID INT ( 11 ) NOT NULL AUTO_INCREMENT COMMENT '自增ID，每条新增记录自增',
	JOBID INT(11) NOT NULL COMMENT '关联SYN_JOB_CONF表的JOBID 获取同步表名',
	NETID INT(11) NOT NULL,
    CALIBERID VARCHAR(6) NOT NULL,
    YMD VARCHAR(8) NOT NULL,
	CREATETIME timestamp NOT NULL COMMENT '创建时间',
	SYNTIME timestamp NULL COMMENT '同步完成时间',
	ENV INT(2) NOT NULL COMMENT '主调->备调(0),备调->主调(1)',
	OPEARATE INT(2) NOT NULL COMMENT 'insert or update(0),delete(1)',
	SYNCOUNT INT(2) DEFAULT 1 COMMENT '需要同步次数，每次修改所需同步表(如base_bus)时此值加1，避免同步时又对所需同步表作修改造成的部分数据缺失',
	SYNSTATUS INT(2) NOT NULL COMMENT '同步状态(0：未同步；1：开始同步；2：完成同步)',
	PRIMARY KEY ( SJCID ) ,
	UNIQUE (NETID,CALIBERID,YMD),
	KEY INDEX_UID_01 (NETID,CALIBERID,YMD),
	KEY INDEX__ESS_01 (ENV,SYNCOUNT,SYNSTATUS),
	KEY INDEX_EOSS_01 (ENV,OPEARATE,SYNCOUNT,SYNSTATUS),
	FOREIGN KEY (JOBID) REFERENCES syn_job_conf(JOBID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT ='主备数据同步状态表，每个需要同步的表对应一个';

DROP TABLE IF EXISTS st_fc_96lc_syn;
CREATE TABLE st_fc_96lc_syn (
	SJCID INT ( 11 ) NOT NULL AUTO_INCREMENT COMMENT '自增ID，每条新增记录自增',
	JOBID INT(11) NOT NULL COMMENT '关联SYN_JOB_CONF表的JOBID 获取同步表名',
	NETID INT(11) NOT NULL,
    CALIBERID VARCHAR(6) NOT NULL,
    YMD VARCHAR(8) NOT NULL,
	CREATETIME timestamp NOT NULL COMMENT '创建时间',
	SYNTIME timestamp NULL COMMENT '同步完成时间',
	ENV INT(2) NOT NULL COMMENT '主调->备调(0),备调->主调(1)',
	OPEARATE INT(2) NOT NULL COMMENT 'insert or update(0),delete(1)',
	SYNCOUNT INT(2) DEFAULT 1 COMMENT '需要同步次数，每次修改所需同步表(如base_bus)时此值加1，避免同步时又对所需同步表作修改造成的部分数据缺失',
	SYNSTATUS INT(2) NOT NULL COMMENT '同步状态(0：未同步；1：开始同步；2：完成同步)',
	PRIMARY KEY ( SJCID ) ,
	UNIQUE (NETID,CALIBERID,YMD),
	KEY INDEX_UID_02 (NETID,CALIBERID,YMD),
	KEY INDEX__ESS_02 (ENV,SYNCOUNT,SYNSTATUS),
	KEY INDEX_EOSS_02 (ENV,OPEARATE,SYNCOUNT,SYNSTATUS),
	FOREIGN KEY (JOBID) REFERENCES syn_job_conf(JOBID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT ='主备数据同步状态表，每个需要同步的表对应一个';

DROP TABLE IF EXISTS st_his_288lc_syn;
CREATE TABLE st_his_288lc_syn (
	SJCID INT ( 11 ) NOT NULL AUTO_INCREMENT COMMENT '自增ID，每条新增记录自增',
	JOBID INT(11) NOT NULL COMMENT '关联SYN_JOB_CONF表的JOBID 获取同步表名',
	NETID INT(11) NOT NULL,
    CALIBERID VARCHAR(6) NOT NULL,
    YMD VARCHAR(8) NOT NULL,
	CREATETIME timestamp NOT NULL COMMENT '创建时间',
	SYNTIME timestamp NULL COMMENT '同步完成时间',
	ENV INT(2) NOT NULL COMMENT '主调->备调(0),备调->主调(1)',
	OPEARATE INT(2) NOT NULL COMMENT 'insert or update(0),delete(1)',
	SYNCOUNT INT(2) DEFAULT 1 COMMENT '需要同步次数，每次修改所需同步表(如base_bus)时此值加1，避免同步时又对所需同步表作修改造成的部分数据缺失',
	SYNSTATUS INT(2) NOT NULL COMMENT '同步状态(0：未同步；1：开始同步；2：完成同步)',
	PRIMARY KEY ( SJCID ) ,
	UNIQUE (NETID,CALIBERID,YMD),
	KEY INDEX_UID_03 (NETID,CALIBERID,YMD),
	KEY INDEX__ESS_03 (ENV,SYNCOUNT,SYNSTATUS),
	KEY INDEX_EOSS_03 (ENV,OPEARATE,SYNCOUNT,SYNSTATUS),
	FOREIGN KEY (JOBID) REFERENCES syn_job_conf(JOBID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT ='主备数据同步状态表，每个需要同步的表对应一个';

DROP TABLE IF EXISTS st_fc_288lc_syn;
CREATE TABLE st_fc_288lc_syn (
	SJCID INT ( 11 ) NOT NULL AUTO_INCREMENT COMMENT '自增ID，每条新增记录自增',
	JOBID INT(11) NOT NULL COMMENT '关联SYN_JOB_CONF表的JOBID 获取同步表名',
	NETID INT(11) NOT NULL,
    CALIBERID VARCHAR(6) NOT NULL,
    YMD VARCHAR(8) NOT NULL,
	CREATETIME timestamp NOT NULL COMMENT '创建时间',
	SYNTIME timestamp NULL COMMENT '同步完成时间',
	ENV INT(2) NOT NULL COMMENT '主调->备调(0),备调->主调(1)',
	OPEARATE INT(2) NOT NULL COMMENT 'insert or update(0),delete(1)',
	SYNCOUNT INT(2) DEFAULT 1 COMMENT '需要同步次数，每次修改所需同步表(如base_bus)时此值加1，避免同步时又对所需同步表作修改造成的部分数据缺失',
	SYNSTATUS INT(2) NOT NULL COMMENT '同步状态(0：未同步；1：开始同步；2：完成同步)',
	PRIMARY KEY ( SJCID ) ,
	UNIQUE (NETID,CALIBERID,YMD),
	KEY INDEX_UID_04 (NETID,CALIBERID,YMD),
	KEY INDEX__ESS_04 (ENV,SYNCOUNT,SYNSTATUS),
	KEY INDEX_EOSS_04 (ENV,OPEARATE,SYNCOUNT,SYNSTATUS),
	FOREIGN KEY (JOBID) REFERENCES syn_job_conf(JOBID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT ='主备数据同步状态表，每个需要同步的表对应一个';

DROP TABLE IF EXISTS st_fc_result_syn;
CREATE TABLE st_fc_result_syn (
	SJCID INT ( 11 ) NOT NULL AUTO_INCREMENT COMMENT '自增ID，每条新增记录自增',
	JOBID INT(11) NOT NULL COMMENT '关联SYN_JOB_CONF表的JOBID 获取同步表名',
	FCNO INT(11) NOT NULL,
	CREATETIME timestamp NOT NULL COMMENT '创建时间',
	SYNTIME timestamp NULL COMMENT '同步完成时间',
	ENV INT(2) NOT NULL COMMENT '主调->备调(0),备调->主调(1)',
	OPEARATE INT(2) NOT NULL COMMENT 'insert or update(0),delete(1)',
	SYNCOUNT INT(2) DEFAULT 1 COMMENT '需要同步次数，每次修改所需同步表(如base_bus)时此值加1，避免同步时又对所需同步表作修改造成的部分数据缺失',
	SYNSTATUS INT(2) NOT NULL COMMENT '同步状态(0：未同步；1：开始同步；2：完成同步)',
	PRIMARY KEY ( SJCID ) ,
	UNIQUE (FCNO),
	KEY INDEX_UID_05 (FCNO),
	KEY INDEX__ESS_05 (ENV,SYNCOUNT,SYNSTATUS),
	KEY INDEX_EOSS_05 (ENV,OPEARATE,SYNCOUNT,SYNSTATUS),
	FOREIGN KEY (JOBID) REFERENCES syn_job_conf(JOBID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT ='主备数据同步状态表，每个需要同步的表对应一个';

DROP TABLE IF EXISTS st_fc_96lc_submit_syn;
CREATE TABLE st_fc_96lc_submit_syn (
	SJCID INT ( 11 ) NOT NULL AUTO_INCREMENT COMMENT '自增ID，每条新增记录自增',
	JOBID INT(11) NOT NULL COMMENT '关联SYN_JOB_CONF表的JOBID 获取同步表名',
	NETID INT(11) NOT NULL,
    CALIBERID VARCHAR(6) NOT NULL,
    YMD VARCHAR(8) NOT NULL,
	CREATETIME timestamp NOT NULL COMMENT '创建时间',
	SYNTIME timestamp NULL COMMENT '同步完成时间',
	ENV INT(2) NOT NULL COMMENT '主调->备调(0),备调->主调(1)',
	OPEARATE INT(2) NOT NULL COMMENT 'insert or update(0),delete(1)',
	SYNCOUNT INT(2) DEFAULT 1 COMMENT '需要同步次数，每次修改所需同步表(如base_bus)时此值加1，避免同步时又对所需同步表作修改造成的部分数据缺失',
	SYNSTATUS INT(2) NOT NULL COMMENT '同步状态(0：未同步；1：开始同步；2：完成同步)',
	PRIMARY KEY ( SJCID ) ,
	UNIQUE (NETID,CALIBERID,YMD),
	KEY INDEX_UID_06 (NETID,CALIBERID,YMD),
	KEY INDEX__ESS_06 (ENV,SYNCOUNT,SYNSTATUS),
	KEY INDEX_EOSS_06 (ENV,OPEARATE,SYNCOUNT,SYNSTATUS),
	FOREIGN KEY (JOBID) REFERENCES syn_job_conf(JOBID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT ='主备数据同步状态表，每个需要同步的表对应一个';

DELETE from `syn_job_conf`;
INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('0','0 */2 * * * ?', '*', '*', 'lf_his_96lc', '*', 'NETID,CALIBERID,YMD', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('0','0 */2 * * * ?', '*', '*', 'st_fc_96lc', '*', 'NETID,CALIBERID,YMD', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('0','0 */2 * * * ?', '*', '*', 'st_his_288lc', '*', 'NETID,CALIBERID,YMD', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('0','0 */2 * * * ?', '*', '*', 'st_fc_288lc', '*', 'NETID,CALIBERID,YMD', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('0','0 */2 * * * ?', '*', '*', 'ST_FC_RESULT', '*', 'FCNO', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('0','0 */2 * * * ?', '*', '*', 'ST_FC_96LC_SUBMIT', '*', 'NETID,CALIBERID,YMD', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'base_substation', '*', 'STATIONID', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'base_bus', '*', 'BUSID', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'base_acline', '*', 'ID', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'base_unit', '*', 'ID', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'base_transformer', '*', 'ID', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'lf_his_96lc_base', '*', 'BUSID,CALIBERID,YMD', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'lf_his_96lc', '*', 'BUSID,CALIBERID,YMD', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'lf_q_his_96lc', '*', 'BUSID,CALIBERID,YMD', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'bus_load_repair_log', '*', 'BUSID,HISDATE,HISTIME', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'bus_fc_96lc_submit', '*', 'BUSID,CALIBERID,YMD', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'bus_fc_q_96lc_submit', '*', 'BUSID,CALIBERID,YMD', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'bus_fc_96lc_submit_modify', '*', 'BUSID,CALIBERID,YMD', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'bus_fc_96lc', '*', 'FCNO,YMD,METHODID', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'lf_net_his_96lc', '*', 'NETID,CALIBERID,YMD', '*','7');

INSERT INTO `syn_job_conf`(`JOBNAME`, `CRON`, `SRCSQL`, `SRCTABLEFIELDS`, `DESTTABLE`, `DESTTABLEFIELDS`, `DESTTABLEKEY`, `DESTTABLEUPDATE`,`SYNCOUNT`) VALUES ('1','0 */2 * * * ?', '*', '*', 'lf_net_fc_96lc', '*', 'NETID,CALIBERID,YMD', '*','7');

INSERT INTO `syn_server_status`(`id`, `createtime`, `updatetime`, `downtime`, `islive`) VALUES (1, '2020-10-31 09:03:00', '2020-10-31 09:03:00', NULL, 0);


-- 对需要同步的表新增字段
-- UPDATE lf_his_96lc SET LASTTIME ='2020-04-26 09:03:00' WHERE YMD ='20210101';
alter table zyc_stlf_nw.lf_his_96lc add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_01 ON lf_his_96lc(LASTTIME);

alter table zyc_stlf_nw.st_fc_96lc add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_02 ON st_fc_96lc(LASTTIME);

-- alter table zyc_stlf_nw.LF_NET_HIS_96LC add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
-- CREATE INDEX index_lt_10 ON lf_his_96lc(LASTTIME);
--
-- alter table zyc_stlf_nw.LF_NET_FC_96LC add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
-- CREATE INDEX index_lt_11 ON zyc_stlf_nw.LF_NET_FC_96LC(LASTTIME);

alter table zyc_stlf_nw.st_his_288lc add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_03 ON zyc_stlf_nw.st_his_288lc(LASTTIME);

alter table zyc_stlf_nw.st_fc_288lc add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_04 ON zyc_stlf_nw.st_fc_288lc(LASTTIME);

alter table zyc_stlf_nw.st_fc_result add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_05 ON zyc_stlf_nw.st_fc_result(LASTTIME);

alter table zyc_stlf_nw.st_fc_96lc_submit add column LASTTIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最新更新时间';
CREATE INDEX index_lt_06 ON zyc_stlf_nw.st_fc_96lc_submit(LASTTIME);

SET FOREIGN_KEY_CHECKS =1;